#!/bin/sh

set -e

script/build

if test -e "./output/index.html";then
  echo "It builds!"
  rm -Rf output
else
  echo "Huh. That's odd. The example site doesn't seem to build."
  exit 1
fi

gem build minima.gemspec
